-- CAMBIO DE BASE DE DATOS
USE Gestion_Escolar
GO

-- CREA LA TABLA ESTUDIANTES
CREATE TABLE Estudiante(
	
	EstudianteID INT IDENTITY (1,1) PRIMARY KEY,
	Usuario NVARCHAR(127) NOT NULL,
	Pswd NVARCHAR(24) NOT NULL,
	Nombres NVARCHAR(127) NOT NULL,
	Apellidos NVARCHAR(127) NOT NULL,
	Cedula NVARCHAR(20) NOT NULL,
	Direccion NVARCHAR(MAX) NOT NULL,
	Genero NVARCHAR(10) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	FechaNacimiento DATETIME NOT NULL,
	PrimerMatricula DATETIME NOT NULL,
	NombrePadre NVARCHAR(127)NOT NULL,
	ApellidosPadre NVARCHAR(127)NOT NULL,
	TelefonoPadre NVARCHAR(11) not null
)
GO

--CAPTURA LA FECHA DE MATRICULA DE FORMA AUTOMATICA
ALTER TABLE Estudiante ADD DEFAULT (getdate()) FOR PrimerMatricula
GO