--CAMBIO BASE DE DATOS
USE Gestion_Escolar
GO

--CREAR TABLA PROFESORES
CREATE TABLE Profesor(
	IDProfesor INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	NombreUsuario NVARCHAR(127) NOT NULL,
	PSWD NVARCHAR(255) NOT NULL,
	Curso INT NOT NULL,
	Nombre NVARCHAR (127) NOT NULL,
	Apellidos NVARCHAR (127)NOT NULL,
	Materias NVARCHAR (31) NOT NULL,
	Direccion NVARCHAR (255) NOT NULL,
	Cedula NVARCHAR(20) NOT NULL,
	FechaNacimiento DATETIME NOT NULL,
	Telefono NVARCHAR(31) NOT NULL,
	Calificacion NVARCHAR(127) NOT NULL,
	Genero NVARCHAR (15) NOT NULL,
	Correo NVARCHAR(255) NOT NULL,
	FechaInicio DATETIME
)
GO

--CAPTURA LA FECHA DE MATRICULA DE FORMA AUTOMATICA
ALTER TABLE Profesor ADD DEFAULT (getdate()) FOR FechaInicio
GO
