--CAMBIO DE BASE DE DATOS
USE Gestion_Escolar
GO

--CREACION DE TABLA
CREATE TABLE Administrador (
	AdminID INT IDENTITY(1,1),
	Usuario	NVARCHAR(127),
	Pswd NVARCHAR(64),
	Nombre NVARCHAR(127),
	Apellido NVARCHAR(127),
	FechaInicio DATETIME,
)

--CAPTURA LA FECHA DE MATRICULA DE FORMA AUTOMATICA
ALTER TABLE Administrador ADD DEFAULT (getdate()) FOR FechaInicio
GO